# ── Imports ───────────────────────────────────────────────────────────
import warnings
warnings.filterwarnings('ignore')
import random
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import csv
from mamba_ssm import Mamba

# ── Reproducibility ───────────────────────────────────────────────────
# fix all random seeds so results are identical every run
torch.manual_seed(333)
np.random.seed(333)
random.seed(333)
torch.cuda.manual_seed_all(333)

# ── Load DGP data ─────────────────────────────────────────────────────
# dgp_data_v2.pt was generated by dgp_mamba.py with seed 333
# contains 500 simulated time series and all hyperparameters
print("Running Mamba rolling forecast on test set...")
data       = torch.load('dgp_data_v2.pt')
samples    = data['samples'] # (500, 1200) full sequences including test
sigma      = data['sigma'] # noise std — theoretical minimum is sigma^2
n_samples  = data['n_samples'] # 500
d_model    = data['d_model'] # embedding dimension — 16
d_state    = data['d_state'] # SSM state dimension — 16
d_inner    = data['d_inner'] # expanded inner dimension — 32
d_conv     = data['d_conv'] # depthwise conv kernel size — 4
T_train    = data['T_train'] # training sequence length — 1150
T_test     = data['T_test'] # test sequence length — 50

# ── Training hyperparameters ──────────────────────────────────────────
n_epochs   = 10000
lr         = 1e-3

# ── Device ────────────────────────────────────────────────────────────
device     = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")
print(f"CUDA available: {torch.cuda.is_available()}")

# ── Create CSV and write header ───────────────────────────────────────
# CSV saves per step metrics immediately after each step completes
# allows monitoring progress live while job is running
with open('mamba_test_per_step2.csv', 'w', newline='') as f:
    writer = csv.writer(f)
    writer.writerow(['step', 'mean_mse', 'std_mse', 'mean_ratio', 'std_ratio'])

# storage for per step summary metrics
all_step_means = []
all_step_stds  = []

# ── Outer loop — forecast steps ───────────────────────────────────────
# step is the outer loop so we get per step metrics across all 500 samples
# at each step we compute mean and std MSE across all 500 samples
for step in range(T_test - 1):
    print(f"\n── Step {step+1}/{T_test-1} ──────────────────────────────────")

    # collect one squared error per sample for this step
    step_errors = []

    # ── Inner loop — samples ──────────────────────────────────────────
    for s in range(n_samples):
        # expanding window — use all data up to current forecast origin
        # at step 0: train on x_1...x_1150, predict x_1151
        # at step 1: train on x_1...x_1151, predict x_1152 etc.
        sample        = samples[s]
        current_train = sample[:T_train + step].unsqueeze(0).to(device)

        # reset seed before every model initialization
        # ensures identical starting weights for every sample at every step
        # removes initialization variance from the comparison
        torch.manual_seed(333)
        np.random.seed(333)
        random.seed(333)
        torch.cuda.manual_seed_all(333)

        # fresh model for each sample at each step
        # embed: projects scalar input to d_model dimensional vector
        # mamba: processes sequence through SSM selective state spaces
        # head:  projects d_model output back to scalar prediction
        embed  = nn.Linear(1, d_model).to(device)
        mamba  = Mamba(d_model=d_model, d_state=d_state,
                       d_conv=d_conv, expand=2).to(device)
        head   = nn.Linear(d_model, 1).to(device)

        # combine all parameters for single optimizer
        all_params = list(embed.parameters()) + \
                     list(mamba.parameters()) + \
                     list(head.parameters())

        optimizer  = torch.optim.Adam(all_params, lr=lr)

        # teacher forcing setup on expanding window
        x_in  = current_train[:, :-1].float()
        x_tgt = current_train[:, 1:].float()

        # ── Fit model on expanding window ────────────────────────────
        # refit from scratch at every step — true rolling forecast
        # weights converge to best fit for all available data up to this step
        for epoch in range(n_epochs):
            embed.train(); mamba.train(); head.train()
            optimizer.zero_grad()

            x_emb = embed(x_in.unsqueeze(-1))
            x_out = mamba(x_emb)
            x_hat = head(x_out).squeeze(-1)

            loss  = F.mse_loss(x_hat, x_tgt)
            loss.backward()
            optimizer.step()

            # print progress every 250 epochs
            if epoch % 250 == 0:
                print(f"Step {step+1:>3d}/{T_test-1} | "
                      f"Sample {s+1:>4d}/{n_samples} | "
                      f"Epoch {epoch:>4d} | "
                      f"Ratio: {loss.item()/sigma**2:.4f}")

            # early stopping — stop when ratio reaches theoretical minimum
            # ratio = MSE / sigma^2, minimum possible value is 1.0
            # stopping at 1.01 prevents overfitting below noise floor
            if loss.item() / sigma**2 <= 1.01:
                print(f"Step {step+1:>3d}/{T_test-1} | "
                      f"Sample {s+1:>4d}/{n_samples} | "
                      f"Early stop at epoch {epoch} | "
                      f"Ratio: {loss.item()/sigma**2:.4f}")
                break

        # ── One step ahead prediction ─────────────────────────────────
        # switch to eval mode — hidden state resets to zero
        # refeeding full expanding window rebuilds hidden state
        # final position hidden state h_{T+step} used for prediction
        # x_pred = predicted x_{T+step+1}
        # x_true = true     x_{T+step+1}
        embed.eval(); mamba.eval(); head.eval()
        with torch.no_grad():
            x_emb  = embed(x_in.unsqueeze(-1)) # rebuild hidden state
            x_out  = mamba(x_emb)
            x_hat  = head(x_out).squeeze(-1)
            x_pred = x_hat[:, -1] # last position = one step ahead
            x_true = sample[T_train + step].to(device).float()
            error  = (x_pred - x_true) ** 2 # squared error for this step

        step_errors.append(error.item())

        print(f"Step {step+1:>3d}/{T_test-1} | "
              f"Sample {s+1:>4d}/{n_samples} | "
              f"Pred: {x_pred.item():.4f} | "
              f"True: {x_true.item():.4f} | "
              f"SE: {error.item():.6f}")

        del embed, mamba, head, optimizer
        torch.cuda.empty_cache()

# ── Per step metrics across all 500 samples ───────────────────────
    # after all 500 samples complete for this step
    # compute mean and std of squared errors across samples
    step_errors = np.array(step_errors)
    step_mean   = step_errors.mean()
    step_std    = step_errors.std()

    all_step_means.append(step_mean)
    all_step_stds.append(step_std)

    print(f"\nStep {step+1} | "
          f"Mean MSE: {step_mean:.6f} | "
          f"Std: {step_std:.6f} | "
          f"Ratio: {step_mean/sigma**2:.4f}")

    # write this step's results to CSV immediately
    # appending one row after each step so progress is visible live
    with open('mamba_test_per_step2.csv', 'a', newline='') as f:
        writer = csv.writer(f)
        writer.writerow([
            step + 1,
            step_mean,
            step_std,
            step_mean / sigma**2,
            step_std  / sigma**2
        ])

# ── Overall summary across all steps and samples ──────────────────────
# average the per step means to get overall rolling forecast MSE
# this is the primary metric for comparing Mamba vs ARMA on test data
all_step_means    = np.array(all_step_means)
all_step_stds     = np.array(all_step_stds)
overall_mean_mfor = all_step_means.mean()
overall_std_mfor  = all_step_means.std()


#save results
np.save('mamba_test_results2.npy', {
    'per_step_means' : all_step_means,
    'per_step_stds'  : all_step_stds,
    'mean_mse'       : overall_mean_mfor,
    'std_mse'        : overall_std_mfor,
})

print(f"\n── Mamba Rolling Forecast Summary ───────────────────────────")
print(f"Mean MSE : {overall_mean_mfor:.6f}")
print(f"Std  MSE : {overall_std_mfor:.6f}")
print(f"Theoretical minimum (sigma^2) : {sigma**2:.6f}")
print(f"Ratio MSE / sigma^2           : {overall_mean_mfor / sigma**2:.4f}")
print("Saved to mamba_test_results2.npy and mamba_test_per_step2.csv")
