# ── Imports ───────────────────────────────────────────────────────────
import warnings
warnings.filterwarnings('ignore')
import random
import numpy as np
import torch
import pmdarima as pm
from collections import Counter

# ── Reproducibility ───────────────────────────────────────────────────
# fix all random seeds so results are identical every run
torch.manual_seed(42)
np.random.seed(42)
random.seed(42)
torch.cuda.manual_seed_all(42)

# ── Load DGP data ─────────────────────────────────────────────────────
# dgp_data_v2.pt was generated by dgp_mamba.py with seed 333
# only need train_data, sigma and n_samples for ARMA training
data       = torch.load('dgp_data_v2.pt')
train_data = data['train_data']
sigma      = data['sigma']
n_samples  = data['n_samples']


# ── Per sample ARMA fitting ───────────────────────────────────────────
# fit a fresh ARMA model independently to each of the 500 samples
# auto_arima selects the best order via AIC information criterion
# this measures how well a linear model can fit the DGP dynamics
print("Fitting Auto ARMA model to each sample...")

arma_sample_mse  = [] # store MSE for each sample
arma_sample_orders = [] # store selected order for each sample

for s in range(n_samples):

    # convert tensor to numpy for pmdarima
    seq = train_data[s].numpy()   # (T_train,)

    try:
        # auto_arima automatically selects best p and q via AIC
        # selects the order that minimizes AIC — balances fit vs complexity
        # d=0 — no differencing since DGP is stationary by design
        # max_p=20 — allow up to AR(20) to give ARMA its best chance
        # max_q=5  — allow up to MA(5)
        # stepwise=True — faster than exhaustive search
        model = pm.auto_arima(
            seq,
            d=0,              # no differencing since we dont assume unit root
            start_p=0,        # minimum AR order to try
            max_p=20,          # maximum AR order to try
            start_q=0,        # minimum MA order to try
            max_q=5,          # maximum MA order to try
            information_criterion='aic',   # use AIC to select order
            stepwise=True,    # stepwise search is faster than exhaustive
            suppress_warnings=True,
            error_action='ignore'
        )

        # in-sample fitted values — what ARMA predicts for each training point
        # this is the teacher forced evaluation — same as Mamba training MSE
        predictions = model.fittedvalues()      # (T_train,)

        # compute MSE and record selected order
        errors     = (predictions - seq) ** 2
        sample_mse = errors.mean()
        best_order = model.order   # (p, d, q)

    except Exception as e:
        # if fitting fails record nan and fallback order
        print(f"Sample {s+1} failed: {e}")
        sample_mse = float('nan')
        best_order = (None, None, None)


    arma_sample_mse.append(sample_mse)
    arma_sample_orders.append(best_order)

    print(f"Sample {s+1:>4d}/{n_samples} | "
          f"Order: {best_order} | "
          f"MSE: {sample_mse:.6f} | "
          f"Ratio: {sample_mse / sigma**2:.4f}")

# ── Summary across all 500 samples ───────────────────────────────────
# remove any nan values from failed fits before computing summary
arma_sample_mse = np.array(arma_sample_mse)
arma_sample_mse = arma_sample_mse[~np.isnan(arma_sample_mse)]

overall_mean_aic = arma_sample_mse.mean()
overall_std_aic  = arma_sample_mse.std()

# count how many times each order was selected across 500 samples
# consistent order selection indicates stable linear structure in DGP
order_counts = Counter(arma_sample_orders)
most_common  = order_counts.most_common(5)

print(f"\n── Auto ARMA Summary across all {n_samples} samples ────────")
print(f"Mean MSE : {overall_mean_aic:.6f}")
print(f"Std  MSE : {overall_std_aic:.6f}")
print(f"Theoretical minimum (sigma^2) : {sigma**2:.6f}")
print(f"Ratio MSE / sigma^2           : {overall_mean_aic / sigma**2:.4f}")
print(f"\nMost commonly selected orders (p, d, q):")
for order, count in most_common:
    print(f"  {order} — selected {count} times")


# count how many times each order was selected across 500 samples
# consistent order selection indicates stable linear structure in DGP
np.save('arma_results_v2.npy', {
    'aic_mse'    : arma_sample_mse,
    'aic_orders' : arma_sample_orders,
    'mean_aic'   : overall_mean_aic,
    'std_aic'    : overall_std_aic,
})

