# -Imports-
import warnings
warnings.filterwarnings('ignore')
import random
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from mamba_ssm import Mamba

# -Setting Seed-
# fix all random seeds so results are identical every run
torch.manual_seed(42)
np.random.seed(42)
random.seed(42)
torch.cuda.manual_seed_all(42)

# -Load Mamba Generated Data-
# dgp_data_v2.pt was generated by dgp_mamba.py with seed 333
# contains 500 simulated time series and all hyperparameters
data      = torch.load('dgp_data_v2.pt')
samples   = data['samples'] # (500, 1200) full sequence
train_data = data['train_data'] # (500, 1150) training portions
sigma     = data['sigma'] # noise std — theoretical minimum is sigma^2
n_samples = data['n_samples'] # 500 samples
d_model   = data['d_model'] # embedding dimension — 16
d_state   = data['d_state'] # SSM state dimension — 16
d_inner   = data['d_inner'] # expanded inner dimension — 32
d_conv    = data['d_conv'] # depthwise conv kernel size — 4
dt_rank   = data['dt_rank'] # delta projection rank — 1
T_train   = data['T_train'] # training sequence length — 1150
n_epochs  = 6000 # maximum epochs per sample
lr        = 1e-3 # Adam learning rate

# -Device-
# use GPU if available for faster training
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")

# -Per sample training loop-
# fit a new Mamba model independently to each of the 500 samples
# this measures how well Mamba can recover the DGP dynamics
print("Fitting model to each sample...")
all_sample_mse = []

for s in range(n_samples):
    # ─ New model for each sample -
    # three components: embedding layer, Mamba block, prediction head
    # embed: projects scalar input to d_model dimensional vector
    # mamba: processes sequence through SSM with selective state spaces
    # head:  projects d_model dimensional output back to scalar prediction
    embed  = nn.Linear(1, d_model).to(device)
    mamba  = Mamba(d_model=d_model, d_state=d_state, d_conv=d_conv, expand=2).to(device)
    head   = nn.Linear(d_model, 1).to(device)

    # combine all parameters for single optimizer
    all_params = list(embed.parameters()) + \
                 list(mamba.parameters()) + \
                 list(head.parameters())

    optimizer = torch.optim.Adam(all_params, lr=lr)

    # ─ Prepare input and target ─
    # feed true x_t to predict x_{t+1}
    # x_in:  x_1, x_2, ..., x_{T-1}  (inputs)
    # x_tgt: x_2, x_3, ..., x_T      (targets — one step ahead)
    seq   = train_data[s].unsqueeze(0).to(device)   # (1, T_train)
    x_in  = seq[:, :-1].float()          # (1, T_train-1)
    x_tgt = seq[:, 1:].float()           # (1, T_train-1)

    # ─ Training Loop ─
    # each epoch processes the full sequence via parallel scan
    # weights updated after every epoch via Adam gradient descent
    for epoch in range(n_epochs):
        embed.train(); mamba.train(); head.train()

        optimizer.zero_grad()

        # forward pass — embed inputs, process through Mamba, predict
        x_emb = embed(x_in.unsqueeze(-1))   # (1, T_train-1, d_model)
        x_out = mamba(x_emb)                # (1, T_train-1, d_model)
        x_hat = head(x_out).squeeze(-1)     # (1, T_train-1)

        # MSE loss over all T_train-1 predictions simultaneously
        loss  = F.mse_loss(x_hat, x_tgt)
        loss.backward()
        optimizer.step()

        # print progress every 250 epochs
        if epoch % 250 == 0:
            print(f"Sample {s+1:>4d}/{n_samples} | "
                  f"Epoch {epoch:>4d} | "
                  f"Loss: {loss.item():.6f} | "
                  f"Ratio: {loss.item() / sigma**2:.4f} ")

        # early stopping — stop when ratio reaches theoretical minimum
        # ratio = MSE / sigma^2, minimum possible value is 1.0
        # stopping at 1.01 prevents overfitting below noise floor
        if loss.item() / sigma**2 <= 1.01:
            print(f"Sample {s+1:>4d}/{n_samples} | "
                  f"Early stop at epoch {epoch} | "
                  f"Ratio: {loss.item() / sigma**2:.4f}")
            break

    # ─ Final evaluation on training data ─
    # switch to eval mode and rerun forward pass with final weights
    # this uses the fully converged weights to get the true training MSE
    # note: hidden state resets to zero and rebuilds through full sequence
    embed.eval(); mamba.eval(); head.eval()

    with torch.no_grad():
        x_emb = embed(x_in.unsqueeze(-1))   # (1, T_train-1, d_model)
        x_out = mamba(x_emb)                # (1, T_train-1, d_model)
        x_hat = head(x_out).squeeze(-1)     # (1, T_train-1)

        errors     = (x_hat - x_tgt) ** 2  # (1, T_train-1)
        sample_mse = errors.mean().item()

    all_sample_mse.append(sample_mse)
    print(f"Sample {s+1:>4d}/{n_samples} | "
          f"Final MSE: {sample_mse:.6f} | "
          f"Ratio: {sample_mse / sigma**2:.4f}")

    # free GPU memory before next sample
    del embed, mamba, head, optimizer
    torch.cuda.empty_cache()


# ─ Summary across all samples ─
# ── Summary across all 500 samples ───────────────────────────────────
# compute mean and std of MSE across all samples
# mean ratio close to 1.0 means Mamba recovered the DGP well
all_sample_mse = torch.tensor(all_sample_mse)
overall_mean_mamba = all_sample_mse.mean().item()
overall_std_mamba  = all_sample_mse.std().item()

# save results
torch.save({
    'all_sample_mse'   : all_sample_mse, # per sample MSE — (500,) tensor
    'overall_mean_mamba': all_sample_mse.mean().item(), # mean MSE across 500 samples
    'overall_std_mamba' : all_sample_mse.std().item(), # std  MSE across 500 samples
}, 'mamba_train_results_v2.pt')

# print final results
print(f"\n── Summary across all {n_samples} samples ──────────────────")
print(f"Mean MSE : {overall_mean_mamba:.6f}")
print(f"Std  MSE : {overall_std_mamba:.6f}")
print(f"Theoretical minimum (sigma^2) : {sigma**2:.6f}")
print(f"Ratio MSE / sigma^2           : {overall_mean_mamba / sigma**2:.4f}")

